# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift_Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift_Project

  target 'RxSwift_ProjectTests' do
    pod 'RxSwift',    '~> 4.3.1'
    pod 'RxCocoa',    '~> 4.3.1'
  end

  target 'RxSwift_ProjectUITests' do
    pod 'RxBlocking', '~> 4.3.1'
    pod 'RxTest',     '~> 4.3.1'
  end

end
